title: Lists and Filtering Algorithms
description: "Social Media for Del Norte High School"
owner_name: Keerthan K
github_username: githubneos
github_repo: "team_teach" 
baseurl: "/team_teach"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - Lists_Algorithims